/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CapoeiraViewer: typeof import('./components/CapoeiraViewer.vue')['default']
    CapoeiraViewerBackUp: typeof import('./components/CapoeiraViewerBackUp.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    ParentBenefits: typeof import('./components/ParentBenefits.vue')['default']
    ProductTile: typeof import('./components/ProductTile.vue')['default']
    QuizCard: typeof import('./components/QuizCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentBenefits: typeof import('./components/StudentBenefits.vue')['default']
    SubjectRadarChart: typeof import('./components/SubjectRadarChart.vue')['default']
  }
}
